### PR TITLE
Rewrite of summary methods

### PR DESCRIPTION
**Pull request by pstjohn**
Here's a possible update to the summary methods. This PR should address the issues raised in #240, #266, (and possibly some new ones introduced in #268).

The output has changed slightly, here's a demo of the new methods:

## Model summary
```python
from cobra.test import create_test_model
model = create_test_model('textbook')
model.optimize()
model.summary()
```

    IN FLUXES        OUT FLUXES    OBJECTIVES
    ---------------  ------------  ----------------------
    o2_e      21.8   h2o_e  29.2   Biomass_Ecol...  0.874
    glc__D_e  10     co2_e  22.8
    nh4_e      4.77  h_e    17.5
    pi_e       3.21

Outputs are sorted first by flux value, then by metabolite ID. It should now handle odd model formats, i.e., 

```python
import cobra
model = cobra.io.read_sbml_model('cemet.xml')
model.optimize()
model.summary()
```
    IN FLUXES      OUT FLUXES      OBJECTIVES
    -------------  --------------  ------------
    nadp    1e+03  lac_L    1e+03  r60  173
    g1p   600      nadph    1e+03
    gtp   496      pi       1e+03
    gln   488      gdp    496
    adp    18.5    amp      9.24

## Model summary with FVA
```python
model.summary(fva=.95)
```

    IN FLUXES                       OUT FLUXES                      OBJECTIVES
    ------------------------------  ------------------------------  ----------------------
    id          Flux  Range         id          Flux  Range         Biomass_Ecol...  0.874
    --------  ------  ------------  --------  ------  ------------
    o2_e       21.8   [19.9, 23.7]  h2o_e       29.2  [25, 30.7]
    glc__D_e   10     [9.52, 10]    co2_e       22.8  [18.9, 24.7]
    nh4_e       4.77  [4.53, 5.16]  h_e         17.5  [16.7, 22.4]
    pi_e        3.21  [3.05, 3.21]  for_e        0    [0, 5.72]
                                    ac_e         0    [0, 1.91]
                                    acald_e      0    [0, 1.27]
                                    pyr_e        0    [0, 1.27]
                                    etoh_e       0    [0, 1.11]
                                    lac__D_e     0    [0, 1.07]
                                    succ_e       0    [0, 0.837]
                                    akg_e        0    [0, 0.715]
                                    glu__L_e     0    [0, 0.636]

here the fluxes get sorted by the flux, then the maximum flux, then the minimum. There could probably be some improvements to how the ranges get formatted, but this seems good enough for now.

## Metabolite summaries
```python
model.metabolites.pyr_c.summary()
```

    PRODUCING REACTIONS -- Pyruvate (pyr_c)
    ---------------------------------------
    %      FLUX  RXN ID      REACTION
    ---  ------  ----------  --------------------------------------------------
    85%   10     GLCpts      glc__D_e + pep_c --> g6p_c + pyr_c
    15%    1.76  PYK         adp_c + h_c + pep_c --> atp_c + pyr_c
    
    CONSUMING REACTIONS -- Pyruvate (pyr_c)
    ---------------------------------------
    %      FLUX  RXN ID      REACTION
    ---  ------  ----------  --------------------------------------------------
    79%    9.28  PDH         coa_c + nad_c + pyr_c --> accoa_c + co2_c + nadh_c
    21%    2.48  Biomass...  1.496 3pg_c + 3.7478 accoa_c + 59.81 atp_c + 0....

This now includes the metabolite ID as well as the name. I'm not sure if we want to mess around with reversing the reaction arrow or stoichiometry, so right now you'll have to pay attention that if the reaction is listed as producing/consuming, the flux means for the _metabolite_, not the _reaction_.

## Metabolite with FVA
```python
model.metabolites.pyr_c.summary(fva=.95)
```

    PRODUCING REACTIONS -- Pyruvate (pyr_c)
    ---------------------------------------
    %      FLUX  RANGE         RXN ID      REACTION
    ---  ------  ------------  ----------  ----------------------------------------
    85%   10     [9.52, 10]    GLCpts      glc__D_e + pep_c --> g6p_c + pyr_c
    15%    1.76  [0, 12.3]     PYK         adp_c + h_c + pep_c --> atp_c + pyr_c
    0%     0     [0, 9.32]     ME2         mal__L_c + nadp_c --> co2_c + nadph_c...
    0%     0     [0, 6.88]     ME1         mal__L_c + nad_c --> co2_c + nadh_c +...
    
    CONSUMING REACTIONS -- Pyruvate (pyr_c)
    ---------------------------------------
    %      FLUX  RANGE         RXN ID      REACTION
    ---  ------  ------------  ----------  ----------------------------------------
    79%    9.28  [3.9, 18.8]   PDH         coa_c + nad_c + pyr_c --> accoa_c + c...
    21%    2.48  [2.35, 2.48]  Biomass...  1.496 3pg_c + 3.7478 accoa_c + 59.81 ...
    0%     0     [0, 8.58]     PPS         atp_c + h2o_c + pyr_c --> amp_c + 2.0...
    0%     0     [0, 5.72]     PFL         coa_c + pyr_c --> accoa_c + for_c
    0%     0     [0, 1.27]     PYRt2       h_e + pyr_e <=> h_c + pyr_c
    0%     0     [0, 1.07]     LDH_D       lac__D_c + nad_c <=> h_c + nadh_c + p...

Now the percentages should make more sense, and the fluxes are sorted by the same function as the model summaries. 

Let me know what you guys think, or if there's any other improvements we should consider.

### CODE REVIEW

**Comment by cdiener** [comment]
Awesome work @pstjohn! I like it a lot. The zero fluxes in the last table are probably not zero but something really small right? Anyway, looks good to me 👍

**Comment by pstjohn** [comment]
They might actually be 0. I don't hide inactive fluxes if the max/min are nonzero. That being said there is some rounding in there that's not controlled via arguments

**Comment by pstjohn** [comment]
Quick commit to make fva ranges follow `floatfmt`.

**Comment by pstjohn** [comment]
RIP my inbox.. up to the repo owners, obviously, but I'd suggest we turn off coveralls comments :)
https://github.com/lemurheavy/coveralls-public/issues/93

**Comment by hredestig** [comment]
is it easy to get html versions of these tables as well for use in the notebooks?

**Comment by hredestig** [comment]
...coveralls should shut up now (I anyway later suggest to move to codecov which I found easier to use with travis and the docker setup)

**Comment by pstjohn** [comment]
There's no html output in this PR, but tabulate does support html output so it probably wouldn't be too difficult to include. We'd just have to define a summary object with __repr__ and _repr_html_ methods. It would be a bit more than just a couple lines though, since I definitely take some liberties in slicing up the tabulate outputs.

**Comment by phantomas1234** [comment]
@hredestig ready to merge this one?

**Pull request merged**
