### PR TITLE
docs: add Zenodo badge to README

### PR DESCRIPTION
**Pull request by Midnighter**
I've enabled this repository on Zenodo. That means every versioned release should create a fixed copy on Zenodo thus creating a permanent record with a DOI of that version.

### CODE REVIEW

**Comment by cdiener** [comment]
The Zenodo tag broke the release workflow. See https://github.com/opencobra/cobrapy/runs/2167933280.

**Comment by Midnighter** [comment]
Well, the release workflow expected a release note corresponding to the version tag which I did not create. I don't see that as a problem.

**Comment by cdiener** [comment]
Oh I see I did not see that this commit was the tagged one.

**Review by synchon — APPROVED** [review]
Looks good.

**Pull request merged**
