### PR TITLE
adding dfba utilities and example

### PR DESCRIPTION
**Pull request by pstjohn**
Relevant to #763 and #452, this implements some utility functions to the model solution to make a simple dFBA implementation feasible. 

I also added an [example](https://github.com/pstjohn/cobrapy/blob/solver_util_edits/documentation_builder/dfba.ipynb) of the resulting DFBA implementation to the documentation.

Lots of credit to @synchon for the code + ideas, and my apologies if this is stepping on SoC project. I ended up needing something simple for a dfba project here and figured others might make use as well.

Definitely let me know if you don't think this belongs in cobrapy proper, but I figured it doesn't actually end up adding all that much code

### CODE REVIEW

**Comment by pstjohn** [comment]
rebased this on the latest devel. The util.__init__ script should already be pulling everything from the solver utils, so these functions should be importable from cobra.util.

**Comment by pstjohn** [comment]
hold off on merging this for today -- I'm trying out a couple other options.. I'll let you know when this is RTM.

**Comment by pstjohn** [comment]
@Midnighter + @synchon, thoughts on this?

**Comment by synchon** [comment]
I think the inclusion of utility functions will help implementation of various methods and especially DFBA. :)

For the example in the docs, I feel we should state the edge cases and also warn the users that it is just a simple prototype and might lead to convergence issues in some cases. I think it would be best to showcase this as an example of the utilities available in cobrapy, which allows for customized implementations. @Midnighter does that sound good?

@pstjohn won't the use of slack variables cause the constraints to be soft (as compared to metabolites which make them hard constraints)? Is the use of soft constraints desired?

**Comment by pstjohn** [comment]
Hmm, I suppose what I've included is what they do in Eq. 3 of [DFBAlab](https://doi.org/10.1186/s12859-014-0409-8). The lp feasibility problem largely seems to work. 

The edge cases I get seems to be in the lexicographic optimization, the tolerances don't always work out and sometimes I'll get an 'infeasible solution' if for instance, a knocked out product is maximized and then used as a constraint for a subsequent product. 

I'd be happy to put in more qualifying language in the documentation saying this isn't a 'production' DFBA implementation. I've used it for some results here though (for a small-scale model), and might be useful to have to compare against a future implementation that's a bit more developed.

**Comment by Midnighter** [comment]
Thanks for adding this. I would just do some nitpicking with docstrings and the like. Can you give me permission to push a commit to your branch? Otherwise I have to push to devel and it's not transparent.

**Comment by pstjohn** [comment]
are you not able to push to pstjohn/solver_util_edits? I have 'Allow edits from maintainers' checked, I'm not sure how else to give you access

**Comment by Midnighter** [comment]
Sorry, I didn't try before asking :smiley:

**Pull request merged**
