### PR TITLE
Add latest releases

### PR DESCRIPTION
**Pull request by cdiener**
Adds the 0.6 and 0.6.1 releases to the page. Does not mention as 0.5.11 as the latest stable release.

### CODE REVIEW

**Comment by cdiener** [comment]
Sure, thanks for all the recent fixes :)

**Comment by hredestig** [comment]
Sorry for being late to the party (weekend and all (; ), but several of the links to the release tags  are broken (e.g. there is no 0.6 release..).

**Comment by pstjohn** [comment]
In more of a general comment: is there a better way to preview some of these changes? Even reviewing changes here seems to be the wrong approach, the diff's to the website source repo are a lot more readable

**Comment by cdiener** [comment]
I could activate Github pages for the website repo. This way changes could
be previewed at https://opencobra.github.io/cobrapy-website.

**Pull request merged**
