### PR TITLE
refactor: cobra.flux_analysis.moma

### PR DESCRIPTION
**Pull request by synchon**
* [x] description of feature/fix
* [x] tests added/passed

This PR adds typing annotations for `cobra.flux_analysis.moma` and its unit tests. It also upgrades the code style for them to maintain Python 3.6+ compatibility.

### CODE REVIEW

**Comment by synchon** [comment]
The failure happened due to the runner not being able to fetch pip wheels. Seems to me like a case to not worry about and hence marking as tests passed.

**Review by Midnighter — APPROVED** [review]
I don't know if 'wild type' or 'wildtype', and the adjective 'wild-type' are used consistently in the documentation 😛 Looks good.

**Comment by synchon** [comment]
I decided to trust spell-checker considering the ambiguities of English language. 😝

**Comment by Midnighter** [comment]
I think the use of wild-type as an adjective is correct here. Just saying that elsewhere in the documentation it's probably not consistently used.

**Comment by synchon** [comment]
I see. 😄

**Pull request merged**
