### PR TITLE
updated getting_started w/ preferred approach for modifying reaction bounds

### PR DESCRIPTION
**Pull request by gregmedlock**
Small addition to Reaction section in getting started documentation to demonstrate preferred method for modifying reaction bounds.

### CODE REVIEW

**Comment by Midnighter** [comment]
Hi Greg, thank you for the initiative. I would like to resolve the discussion on #791 and then put whatever we conclude in the documentation. Does that sound fair?

**Comment by gregmedlock** [comment]
Sounds great @Midnighter -- when the discussion is resolved I'll update the PR.

**Comment by Midnighter** [comment]
Alright, #791 is now merged.

**Comment by gregmedlock** [comment]
Good to go now. Not sure what's up, but the DeprecationWarning you added in #791 doesn't seem to be printing.

**Comment by cdiener** [comment]
I think normal python warnings will not show in Jupyter notebooks but are redirected to the running terminal. We should probably convert all warnings to logger warnings at some point to give more control for handling as well.

**Pull request merged**
