### PR TITLE
Refactor core dictlist to comply with Python 3.6+

### PR DESCRIPTION
**Pull request by akaviaLab**
* [X] description of feature/fix
Refactor dictlist.py and test_dictlist.py to be Python 3.6+ compliant including type hints, f-strings, no *utf-8*, no future imoprts

### CODE REVIEW

**Comment by Midnighter** [comment]
Something seems odd in the way that my commits were integrated. Maybe your local devel branch was not up-to-date when you did your rebase?

**Comment by akaviaLab** [comment]
No it wasn't.
I tried integrating it on GitHub and then pulling it locally, but
that didn't work.
Since this is something that always trips me up which commands and what
order doesnt resolve in this kind of mess?
If you want I can also delete this branch and redo it on the updated devel.

**Comment by Midnighter** [comment]
My usual steps are to do it locally:
```
git checkout devel
git pull
git checkout refactor/core_dictlist
git rebase devel
```
solve conflicts as needed in the last step.

This commit is odd [3d86ec2](https://github.com/opencobra/cobrapy/pull/1164/commits/3d86ec2cade9a3e0206ee7b5eece2bc7ad927fc4), the remote branch got merged into your local branch. You could interactively rebase and pick the commits that should go in or you create a new branch as you say and cherry-pick the right commits.

**Comment by Midnighter** [comment]
Oh, since you're working on a fork:

```bash
git checkout devel
git pull upstream devel
git push
git checkout refactor/core_dictlist
git rebase devel
```

**Comment by akaviaLab** [comment]
Gah. Hate this git behavior. Opened another branch that doesn't have a million commits, see #1169 1169

**Pull request closed without merging**
