### PR TITLE
fix #657

### LINKED ISSUE #657: Modifying reactions with `__imul__` does not update solver constraints
#### Problem description

Modifying the reaction stoichiometry with `__imul__` etc. does not trigger the necessary update in the solver object.

#### Code Sample

```python
In [1]: from cobra.test import create_test_model

In [2]: mod = create_test_model("textbook")

In [3]: mod.reactions.EX_glc__D_e *= 100

In [4]: mod.reactions.EX_glc__D_e.reaction
Out[4]: '100.0 glc__D_e <=> '

In [5]: mod.constraints.glc__D_e.expression
Out[5]: -1.0*EX_glc__D_e + 1.0*EX_glc__D_e_reverse_af641 - 1.0*GLCpts + 1.0*GLCpts_reverse_a52ae

```

#### Actual Output

Constraint coefficient is 1.0.

#### Expected Output

Constraint coefficient should be 100.0.

#### Output of `cobra.show_versions()`

<details>

System Information
==================
OS                      Linux
OS-release     4.14.0-3-amd64
Python                  3.6.4

Package Versions
================
pip                     9.0.1
setuptools             38.4.0
cobra                   0.9.1
future                 0.16.0
swiglpk                 1.4.4
optlang                 1.3.0
ruamel.yaml           0.14.12
pandas                 0.22.0
numpy                  1.14.0
tabulate                0.8.2
python-libsbml         5.16.0
lxml                    4.1.1
scipy                   1.0.0
matplotlib              2.1.2
palettable              3.1.0
</details>

### PR DESCRIPTION
**Pull request by pstjohn**
Also allows `__imul__` to be reversed in context

### CODE REVIEW

**Comment by cdiener** [comment]
Thanks! What about `__iadd__` and co?

**Comment by pstjohn** [comment]
what kind of logic? `add_metabolites` handles contexts already, and `__iadd__` methods end up there eventually. The only thing not covered is manipulations to the gene reaction rule. (which oddly isn't in `__isub__` either)

**Comment by cdiener** [comment]
Ah sorry, my bad. Did not see the part where `add_metabolites` uses `set_linear_coefficients`. I was trying it and was a bit confused, is the following correct?

```Python
In [17]: mod.constraints.glc__D_e.expression
Out[17]: -1.0*EX_glc__D_e + 1.0*EX_glc__D_e_reverse_af641 - 1.0*GLCpts + 1.0*GLCpts_reverse_a52ae

In [18]: mod.reactions.EX_glc__D_e += mod.reactions.EX_glc__D_e

In [19]: mod.constraints.glc__D_e.expression
Out[19]: -3.0*EX_glc__D_e + 3.0*EX_glc__D_e_reverse_af641 - 1.0*GLCpts + 1.0*GLCpts_reverse_a52ae
```

Why is it 3.0 in `Out[19]`? Shouldn't it be 2.0?

**Comment by pstjohn** [comment]
You you'd think so... good question, I can look into it

**Comment by cdiener** [comment]
That would be great :) the fix for imul looks good to me.

**Comment by pstjohn** [comment]
So that may have been a bit of an edge case, the reason we got -3 was because you were adding a the reaction to itself - so `metabolites_to_add` and `self._metabolites` were the same object. (so it gets added together, then gets added again in the cameo logic)

Ultimately I don't know why we had the logic duplicated in the first place.. here I just `set_linear_coefficients` directly from the reaction `_metabolites` object. It might be a bit more run-time overhead if the reaction was huge and only a few metabolites were changing, but that seems like a worthwhile tradeoff for the simpler code.

As a result, we move the code to drop 0 metabolites below the cameo logic so that removed metabolites get updated in the solver.

**Pull request merged**
