### PR TITLE
Try to fix the Matlab bridge

### PR DESCRIPTION
**Pull request by cdiener**
This is a potential fix for the Matlab bridge. Fixes an incorrect type for `model_info["S"]`. Also includes some formatting and docstring fixes.

### CODE REVIEW

**Comment by cdiener** [comment]
@ beacamara could you check whether that works for you? 

You can either clone this PR with the instructions shown at "view command line instructions" below or [download a zip](https://api.github.com/repos/opencobra/cobrapy/zipball/pull/909/head). Then open a terminal in the folder where you cloned/extracted the code, start ipython and run your analysis again. This way if you run any imports it should use the new code. Let me know if you would like more help with that.

Thanks!

**Comment by Midnighter** [comment]
@beacamara another easy way to install this is:

```
pip install https://github.com/cdiener/cobrapy/archive/fix/matlab_bridge.zip
```

**Comment by beacamara** [comment]
Dear @cdiener  and @Midnighter ,

Sorry for not answering you before. I have followed your instructions, but still a error raised.

These are the steps I have followed:

**1. I have downloaded the file : opencobra-cobrapy-6878246.zip

2. unzip : opencobra-cobrapy-6878246
3. install: sudo -H python3.6 -m pip install -e opencobra-cobrapy-6878246/**

beatriz@zobel1:~/software$ sudo -H python3.6 -m pip install -e opencobra-cobrapy-6878246/
Obtaining file:///home/beatriz/software/opencobra-cobrapy-6878246
Requirement already satisfied: depinfo in /usr/local/lib/python3.6/dist-packages (from cobra==0.16.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from cobra==0.16.0)
Requirement already satisfied: numpy>=1.13 in /usr/lib/python3/dist-packages (from cobra==0.16.0)
Requirement already satisfied: optlang>=1.4.2 in /usr/local/lib/python3.6/dist-packages (from cobra==0.16.0)
Requirement already satisfied: pandas>=0.17.0 in /usr/lib/python3/dist-packages (from cobra==0.16.0)
Requirement already satisfied: python-libsbml-experimental==5.18.0 in /usr/local/lib/python3.6/dist-packages (from cobra==0.16.0)
Requirement already satisfied: ruamel.yaml>=0.16 in /usr/local/lib/python3.6/dist-packages (from cobra==0.16.0)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from cobra==0.16.0)
Requirement already satisfied: swiglpk in /usr/local/lib/python3.6/dist-packages (from cobra==0.16.0)
Requirement already satisfied: pipdeptree>=0.13.2 in /usr/local/lib/python3.6/dist-packages (from depinfo->cobra==0.16.0)
Requirement already satisfied: sympy>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from optlang>=1.4.2->cobra==0.16.0)
Requirement already satisfied: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from ruamel.yaml>=0.16->cobra==0.16.0)
Requirement already satisfied: pip>=6.0.0 in /usr/lib/python3/dist-packages (from pipdeptree>=0.13.2->depinfo->cobra==0.16.0)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.6/dist-packages (from sympy>=1.0.0->optlang>=1.4.2->cobra==0.16.0)
Installing collected packages: cobra
  Found existing installation: cobra 0.16.0
    Uninstalling cobra-0.16.0:
      Successfully uninstalled cobra-0.16.0
  Running setup.py develop for cobra
Successfully installed cobra

**4. In the opencobra-cobrapy-6878246/, I have opened a terminal and start ipython to start the analysis**
Here is the result of running the analysis. Let me know if any of the steps I made were not right.
Beatriz

beatriz@zobel1:~/software/opencobra-cobrapy-6878246$ ipython
Python 3.6.8 (default, Aug 20 2019, 17:12:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import cobra                                                                                         

In [2]: %load_ext pymatbridge                                                                                
/usr/local/lib/python3.6/dist-packages/IPython/nbformat.py:13 ShimWarning: The `IPython.nbformat` package has been deprecated since IPython 4.0. You should import from nbformat instead.
Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge-08564bef-2fbd-42aa-9f93-3c7134f1effc
Send 'exit' command to kill the server
/usr/bin/matlab: 1: /usr/local/MATLAB/R2010b/bin/util/oscheck.sh: /lib64/libc.so.6: not found
....MATLAB started and connected!

In [3]: import cobra.test 
   ...: m = cobra.test.create_test_model("textbook")                                                         

In [4]: from cobra.io.mat import model_to_pymatbridge 
   ...: model_to_pymatbridge(m, variable_name="model")                                                       
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-37c3d59af52e> in <module>
      1 from cobra.io.mat import model_to_pymatbridge
----> 2 model_to_pymatbridge(m, variable_name="model")

~/software/opencobra-cobrapy-6878246/cobra/io/mat.py in model_to_pymatbridge(model, variable_name, matlab)
    305     model_info["S"] = 0
    306     temp_S_name = "cobra_pymatbridge_temp_" + uuid4().hex
--> 307     _check(matlab.set_variable(variable_name, model_info))
    308     _check(matlab.set_variable(temp_S_name, S))
    309     _check(matlab.run_code("%s.S = %s;" % (variable_name, temp_S_name)))

/usr/local/lib/python3.6/dist-packages/pymatbridge/pymatbridge.py in set_variable(self, varname, value)
    326         if isinstance(value, spmatrix):
    327             return self._set_sparse_variable(varname, value)
--> 328         return self.run_func('assignin', 'base', varname, value, nargout=0)
    329 
    330     def set_plot_settings(self, width=512, height=384, inline=True):

/usr/local/lib/python3.6/dist-packages/pymatbridge/pymatbridge.py in run_func(self, func_path, *func_args, **kwargs)
    307                                    func_args=func_args or '',
    308                                    dname=dname,
--> 309                                    nargout=nargout)
    310 
    311     def run_code(self, code):

/usr/local/lib/python3.6/dist-packages/pymatbridge/pymatbridge.py in _json_response(self, **kwargs)
    270 
    271     def _json_response(self, **kwargs):
--> 272         return json.loads(self._response(**kwargs), object_hook=decode_pymat)
    273 
    274     def run_func(self, func_path, *func_args, **kwargs):

/usr/local/lib/python3.6/dist-packages/pymatbridge/pymatbridge.py in _response(self, **kwargs)
    226 
    227     def _response(self, **kwargs):
--> 228         req = json.dumps(kwargs, cls=PymatEncoder)
    229         self.socket.send_string(req)
    230         resp = self.socket.recv_string()

/usr/lib/python3.6/json/__init__.py in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    236         check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237         separators=separators, default=default, sort_keys=sort_keys,
--> 238         **kw).encode(obj)
    239 
    240 

/usr/lib/python3.6/json/encoder.py in encode(self, o)
    197         # exceptions aren't as detailed.  The list call should be roughly
    198         # equivalent to the PySequence_Fast that ''.join() would do.
--> 199         chunks = self.iterencode(o, _one_shot=True)
    200         if not isinstance(chunks, (list, tuple)):
    201             chunks = list(chunks)

/usr/lib/python3.6/json/encoder.py in iterencode(self, o, _one_shot)
    255                 self.key_separator, self.item_separator, self.sort_keys,
    256                 self.skipkeys, _one_shot)
--> 257         return _iterencode(o, 0)
    258 
    259 def _make_iterencode(markers, _default, _encoder, _indent, _floatstr,

TypeError: keys must be a string

**Comment by cdiener** [comment]
Hmm this seems to be an issue with `pymatbridge` itself which may be possible given that it has been abandoned since ~4 years. Just to check that the bridge itself works what does the following give you in ipython?

```python
from pymatbridge import Matlab
mlab = Matlab()
mlab.set_variable("a", {"a": 1, "b": "hello"})
```

**Comment by Midnighter** [comment]
@beacamara are you able to test @cdiener 's question?

**Comment by Midnighter** [comment]
Should we merge this hoping it will improve the situation @cdiener? (Probably can't make it worse.)

**Comment by cdiener** [comment]
It' unlikely to break something since it just checks for a None value at some point. The rest is formatting and docstrings fixes.

**Comment by molversmyr** [comment]
@cdiener I have experienced the same issues as @beacamara regarding the `model_to_pymatbridge()`-function. I ran your suggested code:

```Sage
from pymatbridge import Matlab
mlab = Matlab()
mlab.set_variable("a", {"a": 1, "b": "hello"})
```

and that worked without any problems, so I inspected the function further. I discovered that the function itself creates an ordered dictionary with 17 key-value pairs. One of these keys is `rxnGeneMat` which is of type `sparse.dok.dok_matrix`. Within this sparse matrix, there are also key-value pairs, and all the keys are tuples of what I assume to be the position indexes of the sparse matrix. 

By converting `rxnGeneMat` into an array(), there are no longer key-value pairs, and it allows for the function to run. Would converting `rxnGeneMat` into an array be harmful to the purpose of the code in any way? I understand that for models with very large matrices this could pose a problem, but would this be a problem for smaller matrices as well?

**Comment by Midnighter** [comment]
@molversmyr I have opened a new issue to discuss this. Since this is a merged branch and you're raising a new point. Please continue the conversation in #1004.

**Comment by molversmyr** [comment]
@Midnighter No problem.

**Pull request merged**
