### PR TITLE
fix: context manager not properly resetting changes to model.objective

### PR DESCRIPTION
**Pull request by phantomas1234**
https://gitter.im/opencobra/cobrapy?at=5893ae2ad99b1dd03d3247b2

### CODE REVIEW

**Comment by cdiener** [comment]
Hi, could you explain why that works, since the bug was really cryptic.

**Comment by pstjohn** [comment]
Also, why is `@resettable` on model.objective? It would seem that's the highest part of the call stack.

Could we follow something like @cdiener's `add_to_solver()` wrapper, but `modify_solver_objective()`? Then we could check contexts there.

**Comment by cdiener** [comment]
Yeah that's true Reaction.objective_coefficient and model.objective_coefficient do need a reset as well. The problem with just adding `resettable` to Reaction.objetive_coefficient is that it won't work if forward_coef != - backward_coef since it returns 0 in that case and resetting to zero leaves you with both coefs as zero. Currently, `Reaction/Model.objective_coefficient` is tightly integrated with the objective and they are updated automatically upon changes on the low level objective so I think a better solution would be a new decorator `reset_objective` which simply resets the objective accordingly. Than we just decorate the affected 3 functions and done.

**Comment by pstjohn** [comment]
Yeah I've tried a few edits myself but this is definitely a mess 😄 . For instance, calling
`model.objective = model.reactions.ATPM` seems to set `model.solver.objective` twice:
once in `Reaction.objective_coefficient` and again directly, see lines 595:596 in Model.py.

**Comment by pstjohn** [comment]
Hope you don't mind the edits.
Still doesn't seem to be working, this way we can check on CI when we fix the issue.

**Comment by cdiener** [comment]
The gitter bug is fixed. What's failing are some IO tests now...

**Comment by hredestig** [comment]
had a look at this and turns our that IO problem is rather tricky to get right as it boils down to the split-head between what actually decides the objective, `model.solver.objective` or `reaction.objective_coefficient` with something during (un)pickling that doesn't get set correctly. I think the solution is to drop `reaction._objective_coefficient` completely (working on it..)

**Comment by pstjohn** [comment]
Maybe we could roll this in with a larger change to address #371 and the like? I.e., make sure that cobrapy methods are all just thin wrappers around the underlying optlang object?

I just think that would be easier to keep everything consistent.

**Comment by cdiener** [comment]
I agree with @pstjohn. There are several small things that should get adapted. The one where `Reaction.flux` should gets its value from is a complicated one. For instance its possible that LazySolution deems a solution "fresh" but you still get an error accessing the primal value from optlang, since some solvers like cplex have their onw invalidation methods.

**Comment by pstjohn** [comment]
I think its OK if Reaction.flux raises an error.. the old Reaction.x raised errors.
But it would likely allow us to standardize the errors we expect from each method.

**Comment by hredestig** [comment]
fixing this in #377 instead

**Pull request closed without merging**
