### PR TITLE
refactor: cobra.manipulation.modify

### PR DESCRIPTION
**Pull request by synchon**
* [x] description of feature/fix
* [x] tests added/passed

This PR adds typing annotations to `cobra.manipulation.modify` and upgrades it to follow Python 3.6+ standards.

### CODE REVIEW

**Review by Midnighter — CHANGES_REQUESTED** [review]
Thanks for the extension of docstrings and general upgrades.

I have two points that I think should be changed:

1. I think it'd be better to move the `Renamer` class to the top level and pass the `renamer_dict` as an argument to the initialization.
2. Since we're not adding any new attributes or behaviour to the `_GeneEscaper` initialization, I don't see a need to define `__init__` at all.

**Comment by synchon** [comment]
With the latest commits, I hope I have addressed your changes.

**Comment by Midnighter** [comment]
That's strange, we already upgrade pip in the workflow. Shouldn't happen unless tox installs a different version...

**Review by Midnighter — APPROVED** [review]

**Comment by cdiener** [comment]
Same problem as in optlang. Need to require pip>=21.1 in safety and disable it for Python 2 :sob:

**Comment by Midnighter** [comment]
I think it needs to go into the tox dependencies, right?

**Comment by cdiener** [comment]
Yep in the tox dependencies for the safety step.

**Comment by Midnighter** [comment]
Another indirect solution https://github.com/Midnighter/structurizr-python/pull/76/files

**Pull request merged**
