### PR TITLE
refactor: make model.medium pandas df

### PR DESCRIPTION
**Pull request by hredestig**
Make model.medium return data frame instead as nicer to read in
notebooks (backwards compatible)

### CODE REVIEW

**Comment by Midnighter** [comment]
I appreciate that you want to keep the same interface as before but I find a `DataFrame` with many columns and just one row a confusing format. In that case I'd rather use a `Series`. However, I would really like to set the upper and lower bound. So ideally `Model.medium` would return a data frame where the index is the Reaction ID, a column for the compound ID, compound name, lower bound, upper bound. When setting the compound columns could be optional. Can we make this happen with a conversion function or alternative method without breaking the old interface?

**Comment by hredestig** [comment]
I agree.. that wide df is pretty ugly :/ Current behavior of `Model.medium` is however the upper bound of the import, keeping that feature as well as adding reaction ub, lb might get confusing though.. Will think about it..

**Comment by mmundy42** [comment]
So the medium setter still uses a dict for the input but the medium getter returns a DataFrame? That seems a little confusing. I would prefer to keep the dict since I just reworked several packages to use the new medium getter and setter.

**Comment by hredestig** [comment]
In this pr, you can use dataframe or dict for the setter as they behave very similarly, so this is currently backwards compatible. As discussed above though this requires a wide data frame which is kind of ugly...

**Comment by hredestig** [comment]
I'm dropping this one, the benefit doesn't warrant the change.

**Pull request closed without merging**
