### PR TITLE
WIP: Add a code of conduct

### PR DESCRIPTION
**Pull request by Midnighter**
@opencobra/cobrapy-core we need to decide on a contact e-mail address where concerns can be reported.

### CODE REVIEW

**Comment by cdiener** [comment]
I would suggest a committee of 3 people.

**Comment by synchon** [comment]
Or maybe a separate core group e-mail address?

**Comment by Midnighter** [comment]
Yes, I was also thinking a single person is not a good idea. Another problematic situation is that our core team at the moment consists entirely of men. Both for the development core team, as well as for a committee dealing with misconduct more diversity would be a great improvement. I was thinking earlier that we could, at least on the development side, offer closer mentorship for one or two devs from minority groups?

Actually, I should probably bounce this into the mailing list. Especially people in the community who are maybe not completely comfortable making code changes but still want to contribute could very well help with the committee.

**Comment by synchon** [comment]
>  I was thinking earlier that we could, at least on the development side, offer closer mentorship for one or two devs from minority groups?

Definitely a good idea.

**Comment by cdiener** [comment]
I would have suggested @sgalkina. I agree that we should have more diverse contributor/maintainer populations.

**Comment by gregmedlock** [comment]
Myself and @maureencarey can offer to serve on the committee and as points of contact. GLM5UH@virginia.edu and MAC9JC@virginia.edu are, respectively, good contact addresses. We will both be in academia working in the COBRA world long-term so are happy to serve as contacts for the foreseeable future.

**Comment by Midnighter** [comment]
Excellent, I'm glad to see some movement on this. Ideally, there would be one contact email address and we can set up forwarding to whoever is on the committee at the time.

**Comment by gregmedlock** [comment]
I can create a UVA-based listserv that would forward to all committee members. Messages would be archived and private (unless someone filed a Freedom of Information Act [FOIA] request, which all government-affiliated organizations in the USA have to comply with). How does cobrapy_conduct_committee@virginia.edu sound?

**Comment by Midnighter** [comment]
I would love to have an opencobra.org domain but since that's a long shot, setting up such a list sounds good to me. Can we have hyphens instead of underscores, though? :slightly_smiling_face:

**Comment by matthiaskoenig** [comment]
@Midnighter Don't think this is a longshot. I just got the domain `opencobra.org`. Should be activated in a few hours. We can then setup an email service for that such as zoho and should be good to go in a few days.

**Comment by cdiener** [comment]
Either way we should also allow contacting only a subset of the committee in case the report involves any of the sitting members. Everything else would expose the identity of the victim to a potential perpetrator. The hybrid solutions from pytest makes sense https://github.com/pytest-dev/pytest/blob/master/CODE_OF_CONDUCT.md to me.

**Comment by Midnighter** [comment]
> @Midnighter Don't think this is a longshot. I just got the domain `opencobra.org`. Should be activated in a few hours. We can then setup an email service for that such as zoho and should be good to go in a few days.

That is the pro-active way :slightly_smiling_face: I said long shot because opencobra is more than just cobrapy, it also involves the Matlab and Julia community. Of course, it'd be great to have one code of conduct committee for the whole organisation but the tricky part is that there _is_ no formal organisation. So maybe what we should do here is take the lead but ask other communities if they want in on it?

@cdiener that makes a lot of sense to me :+1:

**Comment by matthiaskoenig** [comment]
Everything activated. For now I just forwarded http://opencobra.org to http://opencobra.github.io/. 
I setup an email address cobrapy@opencobra.org for now which works from now on (just mail me privately that I can share the password and access for imap/smtp privately with the core team). Something like contact@opencobra.org could work for a bigger comittee in the future.

I used migadu (https://www.migadu.com/en/index.html) for now which limits the outgoing emails in the free plan, so don't go wild with sending mails from the account for now.

Best Matthias

**Comment by Midnighter** [comment]
Sounds great. I think either conduct@opencobra.org or coc@opencobra.org would be nice addresses to use for this purpose.

**Comment by matthiaskoenig** [comment]
@Midnighter The great part about migadu is that there is no limitation on addresses. So we can just decide on what is the proper address and who is on the board so that they get access to the email. Just let me know when there is consensus then this can be done in 5 minutes. Just tested if all of this works with the `opencobra.org` domain and the respective emails. Looks basically very simple. There would be an email `conduct@opencobra.org` which would be delegated to multiple other addresses (the code of conduct team, e.g. beber@opencobra.org, diener@opencobra.org, ...). These users would get all the `conduct@opencobra.org` information. The code of conduct team would then just add their respective email to their email program. When the team changes we just add/remove addresses from the delegation (works like a team email). There is full SMTP/IMAP integration so no need for web frontends, but just add the address to thunderbird or any other email client.

**Comment by Midnighter** [comment]
@sgalkina are you still up for being a committee member, too, or not so much any longer? Let me know and I will update this PR with the relevant addresses.

**Comment by Midnighter** [comment]
Svetlana has confirmed her position with me. @matthiaskoenig can you set up conduct@opencobra.org to forward to the included virginia.edu and biosustain.dtu.dk addresses, please?

**Comment by Midnighter** [comment]
@maureencarey @sgalkina @gregmedlock many thanks for stepping up and taking on this responsibility. I hope it will be uneventful :wink:

**Pull request merged**
