### PR TITLE
Refactor/reaction var cache

### LINKED ISSUE #437: refactor reaction.{forward,reverse}_variable
pick these variables directly from model.variables, remove _reset_var_cache

### PR DESCRIPTION
**Pull request by hredestig**
Up for discussion, reduced code complexity at the cost of small performance drop (new would be the 'without-cache'):
```
                                                 test  time [ms] without-cache  time [ms] with-cache  fraction
19  test_flux_variability_loopless_benchmark[optla...              1113.724367            746.265023  0.670063
20  test_flux_variability_loopless_benchmark[optla...               959.773490            757.807933  0.789570
3                          test_pfba_benchmark[cplex]               389.964180            310.387058  0.795937
10  test_single_gene_deletion_benchmark[optlang-glpk]                35.182455             28.155406  0.800268
40             test_copy_benchmark_large_model[cplex]               552.882654            450.004078  0.813923
2                          test_pfba_benchmark[cglpk]               521.866651            427.156404  0.818516
41                            test_deepcopy_benchmark                48.778778             40.454661  0.829350
4   test_single_gene_deletion_fba_benchmark[optlan...                46.886242             38.989685  0.831580
14                test_double_gene_deletion_benchmark              1663.158392           1420.478173  0.854085
16     test_flux_variability_benchmark[optlang-cplex]              2749.193002           2359.436442  0.858229
15      test_flux_variability_benchmark[optlang-glpk]              2661.619079           2290.304987  0.860493
23                      test_loopless_benchmark_after                 7.783169              6.722925  0.863777
18             test_flux_variability_benchmark[cplex]              1964.135249           1698.488282  0.864751
24               test_phenotype_phase_plane_benchmark                49.798329             43.147713  0.866449
22                     test_loopless_benchmark_before                11.006345              9.807074  0.891038
27                         test_achr_sample_benchmark                 0.400330              0.360273  0.899941
21                     test_legacy_loopless_benchmark                19.460566             17.647886  0.906854
5   test_single_gene_deletion_fba_benchmark[optlan...               253.314998            229.785151  0.907112
32               test_add_metabolite_benchmark[cplex]                14.472413             13.142722  0.908122
28                        test_optgp_sample_benchmark                 0.564881              0.517831  0.916708
39             test_copy_benchmark_large_model[cglpk]               485.339261            445.895436  0.918729
12         test_single_gene_deletion_benchmark[cglpk]                19.301832             17.770138  0.920645
25                           test_achr_init_benchmark               118.907942            109.567884  0.921451
11  test_single_gene_deletion_benchmark[optlang-cp...               234.913566            219.073125  0.932569
0                   test_pfba_benchmark[optlang-glpk]               430.881221            403.331616  0.936062
1                  test_pfba_benchmark[optlang-cplex]               733.034956            688.055700  0.938640
17             test_flux_variability_benchmark[cglpk]              1788.971856           1703.717418  0.952344
6      test_single_gene_deletion_fba_benchmark[cglpk]                25.797082             24.617206  0.954263
43             test_change_objective_benchmark[cplex]                 0.448279              0.434472  0.969200
37                         test_copy_benchmark[cglpk]                34.474029             33.493656  0.971562
33          test_subtract_metabolite_benchmark[cglpk]                 0.008314              0.008178  0.983701
35          test_add_remove_reaction_benchmark[cglpk]                 0.509812              0.502333  0.985330
13         test_single_gene_deletion_benchmark[cplex]                34.971072             34.498058  0.986474
7      test_single_gene_deletion_fba_benchmark[cplex]                46.939771             46.355869  0.987561
8            test_single_gene_deletion_moma_benchmark               706.641222            706.918383  1.000392
42             test_change_objective_benchmark[cglpk]                 0.446340              0.452594  1.014011
9          test_single_deletion_linear_moma_benchmark               371.087956            380.439313  1.025200
30                               test_benchmark_write                64.404565             67.072186  1.041420
36          test_add_remove_reaction_benchmark[cplex]                 0.518156              0.539864  1.041893
26                          test_optgp_init_benchmark               118.436626            124.092732  1.047756
31               test_add_metabolite_benchmark[cglpk]                15.011445             15.864405  1.056821
38                         test_copy_benchmark[cplex]                28.889293             32.606093  1.128657
34          test_subtract_metabolite_benchmark[cplex]                 0.008303              0.009864  1.188025
29                                test_benchmark_read                17.682991             25.813330  1.459783

``` 

Fixes #437

### CODE REVIEW

**Comment by cdiener** [comment]
I think the loopless FVA differences are due to reaction.flux. Maybe one could make that faster with some trickery (for instance getting the variables from the previous objective which is actually the reaction). Some also seem to be just due to variance. For instance `test_*_sample_benchmark` never calls reaction.forward_variable and still show changes :)

**Comment by hredestig** [comment]
yes there is indeed quite some variation, even setting min-rounds to 20 the measurements are not deterministic. Seems these benchmarks are rather indicative more than exact.

**Comment by hredestig** [comment]
Me too, @Midnighter ?

**Comment by Midnighter** [comment]
Yes, agreed!

**Pull request merged**
