### PR TITLE
Update faq.ipynb

### PR DESCRIPTION
**Pull request by schultzdre**
Included SAMMI as an alternative visualization tool.

### CODE REVIEW

**Comment by cdiener** [comment]
You might want to add it to https://github.com/opencobra/cobrapy-website as well so it can be highlighted at https://opencobra.github.io/cobrapy/packages/.

**Comment by schultzdre** [comment]
Just added it to the website. Thanks!

**Comment by Midnighter** [comment]
@cdiener have you tried out SAMMI? I haven't worked with it since seeing it at COBRA '18. It feels to me like we should have some positive experience with SAMMI before we recommend it in the documentation? Or do you see it as a neutral list of existing tools?

**Comment by cdiener** [comment]
No idea, I was under the impression that it was #2 (neutral list). But I think I would actually prefer removing all tool names and linking directly to the visualization tag on the website (https://opencobra.github.io/cobrapy/tags/visualization/). This would be easier to maintain.

**Comment by Midnighter** [comment]
I have implemented @cdiener's suggestion. Closing this PR in favour of that. Thank you for suggesting it, though @schultzdre

**Pull request closed without merging**
