### PR TITLE
feat: essential genes and reactions

### PR DESCRIPTION
**Pull request by hredestig**
Add convenience functions for getting sets of essential genes and
reactions. Using this in two other packages that both depend on cobrapy
so better move here.

### CODE REVIEW

**Comment by cdiener** [comment]
Those look like slower versions of `single_gene_deletion` and `single_reaction_deletion`. Or is there a difference I don't see?

**Comment by hredestig** [comment]
You're right, making new pr. Although it does say something about unfortunate function name there..

**Comment by cdiener** [comment]
Im also fine with renaming or refactoring the others, but probably leave that for after removing the old solver interface. Also commented on gitter. `abs(flux) > 0.` should be `abs(flux) > atol` where "atol" is the absolute tolerance of the solver.

**Comment by hredestig** [comment]
Agreed, making fix!

**Pull request merged**
