### PR TITLE
refactor: cobra.sampling.optgp

### PR DESCRIPTION
**Pull request by synchon**
* [x] description of feature/fix
* [x] tests added/passed

This PR refactors `cobra.sampling.optgp` module to improve Python 3.6+ compatibility.

### CODE REVIEW

**Review by cdiener — CHANGES_REQUESTED** [review]
Would be great if that would also change all instances of multiprocessing.Pool to use the context manager like:

```python
with mp.Pool(...) as pool:
    ...
```
This was not supported in Python 2.

**Comment by synchon** [comment]
Yes I kept that as I had another PR to replace the old usage of `multiprocessing.Pool` with the use of context managers. There are a few places across the code base which will need this change, hence I would like to take it all in one go. Is that okay?

**Comment by synchon** [comment]
Latest commit is to rebase on current `devel`.

**Review by cdiener — APPROVED** [review]
Makes sense, go ahead.

**Pull request merged**
