### PR TITLE
gapfilling.ipynb bug fix

### PR DESCRIPTION
**Pull request by pablodig**
Hi,
I noticed that the gapfilling.ipynb notebook in the documentation has an error in the second cell: First the reaction is not called correctly. I changed add_reaction() for add_reactions() which the correct way of calling it. Second, the argument in the add_reactions() function needs to be an iterable so I enclosed the reaction.copy() in []. Third, the cell needs to import cobra to work.

Finally, some of the output that I got in the following cells differ a little bit from what you have in the original notebook.

I hope you find these changes useful.

* [x] description of feature/fix
* [x] tests added/passed

### CODE REVIEW

**Review by cdiener — CHANGES_REQUESTED** [review]
Hi, sorry for the delay. That is looking good. Could you rerun it in an environment with only GLPK or set this as the solver with a Configuration singleton? Since the default package only comes with GLPK that is probably a better reference for the docs. Thanks!

**Comment by cdiener** [comment]
Perfect, thanks!

**Review by cdiener — APPROVED** [review]
Thanks!

**Comment by pablodig** [comment]
Sure. Im happy to help. 
Great package by the way.

**Pull request merged**
