### PR TITLE
WIP: Fix to model summary methods

### LINKED ISSUE #267: list index error in model summary
Using for example the model at https://github.com/cdiener/corda/blob/master/corda/data/cemet.xml calling

```python
model.optimize()
model.summary()
```

gives 
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cdiener/.local/lib/python3.5/site-packages/cobra/core/Model.py", line 376, in summary
    return model_summary(self, **kwargs)
  File "/home/cdiener/.local/lib/python3.5/site-packages/cobra/flux_analysis/summary.py", line 132, in model_summary
    out_fluxes = pd.Series({r.reactants[0]: r.x for r in out_rxns})
  File "/home/cdiener/.local/lib/python3.5/site-packages/cobra/flux_analysis/summary.py", line 132, in <dictcomp>
    out_fluxes = pd.Series({r.reactants[0]: r.x for r in out_rxns})
IndexError: list index out of range
```

The error occurs since it is assumed that all reactions always have reactants. However, that does not have to be the case, particularly if not using boundary metabolites. I could set up a fix but do not understand the logic of using only the first reactant for the summary, could you give me a hint what this is supposed to do @pstjohn? 

Cheers

### PR DESCRIPTION
**Pull request by pstjohn**
This fix resolves #267, in which models that do not conform to the
standard boundary reaction format would cause the `model_summary` method
to fail. Now the summary method will print the ID of the first
metabolite and raise a warning if a boundary reaction exchanges more
than one species.

### CODE REVIEW

**Comment by pstjohn** [comment]
Good catch -- I'll work on that.
You're right, splitting coupled boundary reactions shouldn't be too tough either

**Comment by cdiener** [comment]
Awesome. If you need help with anything you know where to find me :)

**Comment by pstjohn** [comment]
While I'm at it we might as well get to #266, #238, and #240.

How would we feel about exporting table formatting to a third party? It might make the code a bit more extendable / maintainable. [tabulate](https://pypi.python.org/pypi/tabulate) looks promising, but I'm certainly happy to look at others if you have suggestions. (Or if we want to avoid additional dependencies)

**Comment by cdiener** [comment]
I agree. This kind of formatting usually has hundreds of edge cases one has to consider ("what happens if the name of the reaction is super long", etc.). I like how it's done now with converting everything to a pandas data frame and then writing some formatting for that data frame. `tabulate` looks good, we just have to check how it deals with long strings and how it plays with pandas  (for instance the reaction strings). In terms of dependencies I think everything that does not have compiled code is fine.

**Comment by hredestig** [comment]
pardon the premature merge, the bug fix was already good, please open new pr for the additional issues you mentioned. Anyway, tabulate looks like good option, prettytable is another but tabulate directly takes pandas df so maybe the better option.

**Comment by pstjohn** [comment]
Yikes, as @cdiener mentioned there was still an issue with assigning input and output fluxes..
I'll try to send in another PR soon that fixes the current master then.

**Comment by hredestig** [comment]
ouch, yes mea culpa :( This also reminds me I think it would be good to start doing merges to devel first, and only upon release to master..

**Comment by cdiener** [comment]
I think there is no problem here. The bug I reported initially was already fixed here and the rest can be in another pull req. I think bug fix pull requests are fine in master, otherwise master would just be a glorified tag for the latest release :)

**Comment by pstjohn** [comment]
Sounds great. Regardless, it shouldn't be too long until I have a newer implementation ready.
Tabulate seems to be working great, and should make maintenance for these methods a lot easier going forward.

**Pull request merged**
